export type RavelryPattern = {
  free: boolean;
  id: number;
  name: string;
  permalink: string;
  personal_attributes: null;
  first_photo: RavelryPhoto;
  designer: RavelryDesigner;
  pattern_author: RavelryDesigner;
  pattern_sources: RavelryPatternSource[];
};

export type RavelryPhoto = {
  id: number;
  sort_order: number;
  user_id: number;
  x_offset: number;
  y_offset: number;
  square_url: string;
  medium_url: string;
  thumbnail_url: string;
  small_url: string;
  medium2_url: string;
  small2_url: string;
  caption: string | null;
  caption_html: string | null;
  copyright_holder: string | null;
};

export type RavelryDesigner = {
  crochet_pattern_count: number;
  favorites_count: number;
  id: number;
  knitting_pattern_count: number;
  name: string;
  patterns_count: number;
  permalink: string;
  users: RavelryUser[];
};

export type RavelryUser = {
  id: number;
  username: string;
  tiny_photo_url: string;
  small_photo_url: string;
  photo_url: string;
};

export type RavelryPatternSource = {
  amazon_rating?: number;
  amazon_reviews?: number;
  amazon_sales_rank?: number;
  amazon_updated_at?: number;
  amazon_url?: string;
  approved_patterns_count?: number;
  asin: string;
  author: string;
  author_pattern_author_id: number;
  author_surname: string;
  book_binding: null;
  completed: boolean;
  created_at: Date;
  created_by_user_id: number;
  designer_pending_patterns_count: number;
  designer_users_count: number;
  editorships_count: number;
  favorites_count: number;
  first_photo_id: null;
  flaggings_count: number;
  fulfilled_by_ravelry: boolean;
  has_photo: boolean;
  id: number;
  isbn_13: number | null;
  issue: null;
  keywords: string;
  label?: string;
  large_image_url?: string;
  last_pattern_edit: Date;
  link_id: number;
  list_price: null;
  lock_version: number;
  medium_image_url?: string;
  name: string;
  out_of_print: boolean;
  pattern_source_type_id: number;
  patterns_count: number;
  pending_patterns_count: number;
  periodical: boolean;
  permalink: string;
  photos_permitted: boolean;
  popularity: number;
  popularity_rank: number;
  price: null;
  publication_date: null;
  publication_date_set: 0;
  publication_day_set: 0;
  publication_sort_order: null;
  publication_year: null;
  publisher_id: null;
  shelf_image_path: null;
  shelf_image_size: null;
  small_image_url: null;
  source_group_id: null;
  stickies_count: number;
  store_id: number;
  updated_at: Date;
  url: string;
  work_id: null;
  notes: string;
};
